### PR TITLE
LPS-95412 Members count is not updated when conjunctions are changed

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/bryceosterhaus/liferay-portal/pull/45. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
