### PR TITLE
LPS-101616 Update hook usage in segments-experiment-web

### PR DESCRIPTION
**Pull request by wincent**
Hi @andresfulla (cc: @dgarciasarai).

I extracted the `useEventListener()` hook into a common location. I've already sent this over to Brian [here](https://github.com/brianchandotcom/liferay-portal/pull/78396) along with the change to update layout-content-page-editor-web but wanted to give you a heads up. Please let me know if anything looks off here.

### CODE REVIEW

**Comment by wincent** [comment]
Also sent https://github.com/4lejandrito/liferay-portal/pull/324 over to @4lejandrito for similar review.

**Comment by wincent** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
Other than the tests failure there, this looks great from our side. Thanks!

**Comment by wincent** [comment]
> Other than the tests failure there, this looks great from our side. Thanks!

Fingers crossed it is only a glitch in The Matrix!

**Pull request closed without merging**
