### PR TITLE
LPS-91063 Support collection property type in criteria editor

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-91063

My changes: a3b20d4...1a444b1

Backend changes are in https://github.com/thektan/liferay-portal/pull/26

### CODE REVIEW

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68823. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
