### PR TITLE
LPS-101638 | Avoid URLSearchParams in form submission, in segments-simulation-web

### PR DESCRIPTION
**Pull request by markocikos**
Hi @andresfulla ,

Please review the code.

Thank you!

/cc @jbalsas

### CODE REVIEW

**Comment by andresfulla** [comment]
Hi @markocikos , both commits look good to me. Thanks!

**Comment by markocikos** [comment]
@andresfulla If all is ok, please forward to @brianchandotcom

Thank you!

**Comment by andresfulla** [comment]
Just started reviewing 💃 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78828. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
