### PR TITLE
LPS-94791

### PR DESCRIPTION
**Pull request by dgarciasarai**
wip special characters

### CODE REVIEW

**Comment by andresfulla** [comment]
@dgarciasarai  Looks promising. I'm missing the transformation at both ends: `escape` `unescape` so the user consume the same thing as it did before this parsing. Does that makes sense?

**Comment by dgarciasarai** [comment]
Of course!!

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
❤️

**Comment by andresfulla** [comment]
ci:reopen

**Pull request closed without merging**
