### PR TITLE
LPS-108343 Format Content Performance panel numbers

### PR DESCRIPTION
**Pull request by dgarciasarai**
I talked to Greg and now we can name our files without `.es.` extension. 
I did the change here https://github.com/andresfulla/liferay-portal/pull/212/commits/7674dafe6924e05504412c443a08899a26a0f1cb

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
Reviewing! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84558. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84560. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
