### PR TITLE
LPS-87159 [FE] Display entity selector for id type fields in criteria builder

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-87159

This is rebased on LPS-88939 https://github.com/bryceosterhaus/liferay-portal/pull/17.

My changes for this ticket specifically: 2b6be11 and 2b6be11...83f814c (For some reason 050be54...83f814c to include the first commit doesn't work)

### CODE REVIEW

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Looks great! 👍

**Review by andresfulla — COMMENTED** [review]
Looks great! 👍

We'll find-tune interaction at some point.

We also should start implementing error boundaries.

**Comment by thektan** [comment]
PR sent to Bryce https://github.com/bryceosterhaus/liferay-portal/pull/19

**Pull request closed without merging**
