### PR TITLE
LPS-98821 Return segments experience id

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/69. [See changes here.](https://github.com/andresfulla/liferay-portal/compare/dcb64b30832c~1...dcb64b30832c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
