### PR TITLE
LPS-109802 Test failures in segments-web

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-109802](https://issues.liferay.com/browse/LPS-109802).<br><br>Hey @andresfulla, this updates some test snapshots. Markup was changed here: 61fd998a73fc, but the snapshots were not updated then. Please let me know if this is not the correct approach. Thank you!<br><br>/cc @pei-jung

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
many thanks @drewbrokke !!

We already sent the updated snapshots here https://github.com/brianchandotcom/liferay-portal/pull/85744#issuecomment-594709032

**Comment by drewbrokke** [comment]
Thanks @andresfulla!

**Pull request closed without merging**
