### PR TITLE
LPS-98949 Standardize Ajax requests in segments modules

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77501. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/sandrodw3/liferay-portal/pull/139. [See changes here.](https://github.com/andresfulla/liferay-portal/compare/ec2e0cac341d~2...ec2e0cac341d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
