### PR TITLE
LPS-102764 Add tests

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Review by andresfulla — CHANGES_REQUESTED** [review]
The `describe` `name` parameter contains the status of the test. We can either change that or move the new tests.

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
Just started reviewing 💃 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79829. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
