### PR TITLE
LPS-102764 Follow up to add tests

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
Just started reviewing 💃 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79876. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
