### PR TITLE
LPS-100638 | Apply new Session utilities in segments

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by andresfulla** [comment]
Thanks. This looks fine by me. I'll work on top of it today, just to make sure everything still behaves as expected, and I'll sent it.

**Comment by jbalsas** [comment]
👍

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77860. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
