### PR TITLE
LPS-98821 Update fragment entry links editable values with new experience

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/74. [See changes here.](https://github.com/andresfulla/liferay-portal/compare/94151c6a957b~1...94151c6a957b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
