### PR TITLE
LPS-99184 Regen

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/78. [See changes here.](https://github.com/andresfulla/liferay-portal/compare/e08a8d08f71b~2...e08a8d08f71b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/914. [See changes here.](https://github.com/andresfulla/liferay-portal/compare/b82ab80b916b~6...b82ab80b916b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
