### PR TITLE
LPS-105105 Tests and error throwing

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Reviewing! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/1003. [See changes here.](https://github.com/andresfulla/liferay-portal/compare/e14f18f2674d~5...e14f18f2674d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
