### PR TITLE
LPS-94575 No date selector available on segments in IE11

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Pull request submitted to https://github.com/bryceosterhaus/liferay-portal/pull/44. [See changes here.](https://github.com/andresfulla/liferay-portal/compare/b2a55332f62f~2...b2a55332f62f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
